# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kcompletion': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kjobwidgets': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kwallet': '@stable'
    'frameworks/kwidgetaddons': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'libraries/phonon': '@stable'
