/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a collectionadaptor -- org.kde.juk.collection.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COLLECTIONADAPTOR_H_272971151656658
#define COLLECTIONADAPTOR_H_272971151656658

#include <QtCore/QObject>
#include <QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.juk.collection
 */
class CollectionAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.juk.collection")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.juk.collection\" >\n"
"    <method name=\"playlists\" >\n"
"      <arg direction=\"out\" type=\"as\" />\n"
"    </method>\n"
"    <method name=\"openFile\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"file\" />\n"
"    </method>\n"
"    <method name=\"openFile\" >\n"
"      <arg direction=\"in\" type=\"as\" name=\"files\" />\n"
"    </method>\n"
"    <method name=\"openFile\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"playlist\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"file\" />\n"
"    </method>\n"
"    <method name=\"openFile\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"playlist\" />\n"
"      <arg direction=\"in\" type=\"as\" name=\"files\" />\n"
"    </method>\n"
"    <method name=\"createPlaylist\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"list\" />\n"
"    </method>\n"
"    <method name=\"remove\" />\n"
"    <method name=\"removeTrack\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"playlist\" />\n"
"      <arg direction=\"in\" type=\"as\" name=\"files\" />\n"
"    </method>\n"
"    <method name=\"playlist\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"playingPlaylist\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"setPlaylist\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"playlist\" />\n"
"    </method>\n"
"    <method name=\"playlistTracks\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"playlist\" />\n"
"      <arg direction=\"out\" type=\"as\" />\n"
"    </method>\n"
"    <method name=\"trackProperty\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"file\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"property\" />\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"open\" >\n"
"      <arg direction=\"in\" type=\"as\" name=\"files\" />\n"
"    </method>\n"
"    <method name=\"open\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"playlist\" />\n"
"      <arg direction=\"in\" type=\"as\" name=\"files\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CollectionAdaptor(QObject *parent);
    virtual ~CollectionAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void createPlaylist(const QString &list);
    void open(const QString &playlist, const QStringList &files);
    void open(const QStringList &files);
    void openFile(const QString &playlist, const QStringList &files);
    void openFile(const QString &playlist, const QString &file);
    void openFile(const QStringList &files);
    void openFile(const QString &file);
    QString playingPlaylist();
    QString playlist();
    QStringList playlistTracks(const QString &playlist);
    QStringList playlists();
    void remove();
    void removeTrack(const QString &playlist, const QStringList &files);
    void setPlaylist(const QString &playlist);
    QString trackProperty(const QString &file, const QString &property);
Q_SIGNALS: // SIGNALS
};

#endif
