/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a searchadaptor -- org.kde.juk.search.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "searchadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SearchAdaptor
 */

SearchAdaptor::SearchAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SearchAdaptor::~SearchAdaptor()
{
    // destructor
}

QString SearchAdaptor::searchText()
{
    // handle method call org.kde.juk.search.searchText
    QString out0;
    QMetaObject::invokeMethod(parent(), "searchText", Q_RETURN_ARG(QString, out0));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->searchText();
    return out0;
}

void SearchAdaptor::setSearchText(const QString &text)
{
    // handle method call org.kde.juk.search.setSearchText
    QMetaObject::invokeMethod(parent(), "setSearchText", Q_ARG(QString, text));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->setSearchText(text);
}


#include "searchadaptor.moc"
