/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a searchadaptor -- org.kde.juk.search.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SEARCHADAPTOR_H_245651150966917
#define SEARCHADAPTOR_H_245651150966917

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.juk.search
 */
class SearchAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.juk.search")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.juk.search\" >\n"
"    <method name=\"searchText\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"setSearchText\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"text\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    SearchAdaptor(QObject *parent);
    virtual ~SearchAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString searchText();
    void setSearchText(const QString &text);
Q_SIGNALS: // SIGNALS
};

#endif
